name: meal_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_svg: ^2.1.0

  go_router: ^14.6.2

  flutter_bloc: ^9.1.1
  scrollable_positioned_list: ^0.3.8

  freezed_annotation: ^2.4.1

  http: ^1.4.0
  rxdart: ^0.28.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/config/gen/
  line_length: 100

  integrations:
    flutter_svg: true
